### ISSUE TITLE
True Black Dark Mode?

### ISSUE THREAD

**Issue by thatcube** [specfm/design-details#12]
How do you feel guys feel about using a true black color (#000) for dark mode?

Here's a great article that made me second guess using a true black color
https://medium.com/lookup-design/designing-a-dark-theme-for-oled-iphones-e13cdfea7ffe

In a nutshell, the author recommends using an almost black, dark gray color, instead of true black to avoid black smearing with OLED screens. It also recommends not using a true white color (#fff) on a very dark/black background to avoid improve readability and avoid "Halation effect".

I noticed the black smearing within iOS 13 as soon as the beta was released and I tested out the dark mode, but I didn't really understand what was happening or why it was like that. I feel like this is something more designers should know about.

**Comment by brianlovin** [comment]
Discussed in-depth on today's episode: https://spec.fm/podcasts/design-details/310206
