### ISSUE TITLE
Facebook Paper

### ISSUE THREAD

**Issue by jozhouzheng** [specfm/design-details#120]
Hey Brian and Marshall, 

In the latest episode, you mentioned that you will link the article with the videos of fb paper in the show notes. But I couldn't find any links in the episode description or articles on designdetails.fm

Could you please point me to the right direction? Thank you!

Not sure how I will get a response here on github, but my email is jo.zhouzheng@gmail.com

Thank you!
Jo

**Comment by brianlovin** [comment]
Hey Jo - here's the post: https://brianlovin.com/design-details/paper-facebook-ios - I'll add that to the show notes, thanks for the heads up!
