### ISSUE TITLE
Interaction design hand-off

### ISSUE THREAD

**Issue by ericgendreau** [specfm/design-details#157]
Hey Brian and Marshall, 

What are some best practices for handing off interaction design specs to developers? While there are many tools that automate red-lining for visual design, I have trouble documenting interaction design. Using Keynote files is arduous when updating mockups and not very collaborative working across disciplines, but there is a single source of truth for the latest spec. Online design tools that provide commenting are great for sparking conversations and collaborating with developers, as well as ensuring the latest mocks are available to the devs, but the temporal nature of comments and the replacement of mockups may lead to lost specs.

Love the show!
Eric

**Comment by brianlovin** [comment]
Discussed in https://spec.fm/podcasts/design-details/315921
