### ISSUE TITLE
What are some UX mistakes that are counter-intuitive and prevalent? 

### ISSUE THREAD

**Issue by pawsys** [specfm/design-details#16]
A couple of episodes back you said that creating experiences is a lot harder than creating interfaces. Could you expand on this topic? Could you list some examples of common mistakes when creating experiences? What are some UX mistakes that are counter-intuitive and prevalent?

Thanks for making this show. It helped me fill in some missing design-mental-models. I also really enjoy the new format with Marshal. 🙌

**Comment by brianlovin** [comment]
Discussed here: https://designdetails.fm/episodes/318763
