### ISSUE TITLE
Why are product development teams structured the way they are?

### ISSUE THREAD

**Issue by brandonweiss** [specfm/design-details#17]
I’m trying to avoid saying the words “should designers code” and unintentionally bringing about The End of Days, but, I’d be curious to hear your thoughts on why most product development teams are structured the way they are.

It seems like most modern software companies have cross-functional teams. That is, a team made up of at least one product person, designer, and programmer. But the people are rarely if ever cross-functional themselves. In theory the three disciplines are supposed to collaborate, but the results of that collaboration seem to be about what you could expect if you tried to get three people from the dark ages, each from a different continent, and each speaking a completely different language, to build a spaceship together.

My unpopular opinion is that the disciplines of product, design, and programming are intrinsically linked to a degree that makes it extremely difficult to do a great job if you only understand one discipline.

This is entirely anecdotal, but it seems like the companies doing the best work, for the least amount of effort, with the most enjoyment, and have the highest average tenure, tend to primarily hire multi-disciplinary people that are able to very closely collaborate with each other because of their deep understanding of two, if not all three of the disciplines.

And yet, the number of companies that hire and work that way is so small (relative to the total number of software companies) that they could be a rounding error. Why do you think that is?

**Comment by brandonweiss** [comment]
Thanks for riffing on my question—I love hearing people’s thoughts on this!

I hope it was clear that my analogy was a bit tortured and more comedic than literal 🙃 Obviously every company and team is different, and some people get super lucky and wind up at places where everyone is a little cross-functional. When I’ve been lucky enough to find that myself it’s been fantastic, but more often than not I’ve been on teams where everyone else is very siloed, and I think it really shows in how the team communicates and ultimately in the quality of the work. I’ll caveat that I’m an engineer with (I think) a decent understanding of product and design, so from my perspective, when I see product and design work, it often seems to me that the people who produced it don’t really understand the medium they’re building in (engineering/software). And this of course goes the other way, too, when an engineer doesn’t understand anything about product or design.

I completely agree with you regarding unicorns. It’s almost impossible to find people who are truly excellent at 3+ different disciplines. There are so few of them that they might as well be mythological. But I do think it’s feasible, as you mentioned, to find people who are `I` or at least `T` shaped. Everyone knowing just enough about what the other person does to “speak their language” well can make the work orders of magnitude better 👌🏼

The point you made about people trying to gatekeep their role is super interesting. That’s the type of thing that almost no one would probably admit to doing because it’s so optically bad, but there’s definitely a lot of that happening. Looking back on my own experience, it seems like the people who were most likely to act that way were the ones who weren’t particularly skilled and lacked understanding of other roles—they wanted everyone to stay in their lane and really didn’t like anyone “touching their things”. Which while I don’t think is good, is a very understandable, human reaction.

**Comment by brianlovin** [comment]
Thanks for the comment Brandon! We will call this out in followup in 2 episodes from now (already have this week's recorded 😛 

Original episode where we discussed this: https://spec.fm/podcasts/design-details/310638
