### ISSUE TITLE
Self Assessments

### ISSUE THREAD

**Issue by KevinGutowski** [specfm/design-details#212]
So I was going to leave a bunch of questions before but then it pretty much turned into stuff that I really should talk about with my boss… and that, in turn, ended up making a fair amount of the content of my self assessment for this year (which I just started doing now that I am at a larger company). My questions for the show are:

What do you think of self assessments? Do you do them at your current job? How often do you do them? What do they look like? What are some of the questions that you answer? Are they a part of how you can get a raise? What makes a good assessment experience or a bad one? I wanna know the deets so I can compare notes 👀

Thanks! ✌️

**Comment by brianlovin** [comment]
Discussed in https://spec.fm/podcasts/design-details/316506
