### ISSUE TITLE
Figma doesn't have Abstract—how do you organize versioning?

### ISSUE THREAD

**Issue by fromcortes** [specfm/design-details#229]
Hey Brian and Marshall,

Long time listener of the podcast (since episode 1!) but long time lurker until now. Love the podcast so much and thank you for all your hard work.

Been a user of Figma for a few years and love it so much. However, I run into issues on product teams where file management and versioning without having something like Abstract is confusing and wanted some input!

Without Abstract, how can I pass off a file to a developer and be able to work on the next iteration of something in that same file? I've run into issues where I'll give a developer a link to a file but by the time it gets on their plate we may have worked on an iteration that is out of scope for that sprint.

I've tried creating files on a per ticket basis (with JIRA) and having a master file that is on par with what is in production and not, but that leads to a huge amount of files over time and a lot of upkeep for master. I've thought about other ways to do this but haven't come up with a scalable option. Figma's built-in versioning is too limited and inconsistent for a team's needs, and doesn't fix the design changing scope.

Any ideas or experience here on how you manage your files in terms of versioning and iteration you can share that works for PMs, developers, designers, etc?

**Comment by brianlovin** [comment]
Discussed in https://designdetails.fm/episodes/318485 - let us know if there's any follow up we should dig into here!

**Comment by billgalloway** [comment]
Zeplin works great for me.
