### ISSUE TITLE
Giving upward feedback to your senior designers as a not so senior designer. 

### ISSUE THREAD

**Issue by kelle-yess** [specfm/design-details#233]
Hey! I love the podcast and am writing in about upward feedback. Your somewhat latest podcast on giving self feedback (or review) was great. I am a designer fresh out of college that works on a very small team and I struggle with knowing when and how to give upward feedback. I will see things in designs that do not look right and call it out, but sometimes it feels like I'm not being heard, brushed aside, or often the senior designer will push back on the feedback.  When they push back, the conversation comes to a stand still - like we are in a desert eyeing each other with our hands near our waste belts waiting for the other to pull the gun first. 

How do you push back against push back? Should you? How do you end a feedback loop that is going badly? If your senior designers are not listening, what should you do?  How can you bring up that "it feels like you're not taking my opinion seriously" without saying it like this? 

Thanks for your inspiring and educational show!

**Comment by brianlovin** [comment]
Discussed in today's episode! https://spec.fm/podcasts/design-details/317074
