### ISSUE TITLE
What about brutalism? 

### ISSUE THREAD

**Issue by dnlbtlr** [specfm/design-details#253]
hey guys, have you covered the movement of brutalism in design, and how its resurgence can be used to break out of  the "design dogmas"  in web design which have created a kind of banal /sameness to what we see online. i.e. sites are clearly functional but have lost brand personality. I've recently been thinking about how these new dogmas of web have perhaps led to a democratization of design  and less opportunity for more senior designers to flex their creativity. Thoughts?

**Comment by brianlovin** [comment]
We discussed brutalism a bit in last week's Sidebar - hope it is useful here! https://designdetails.fm/episodes/77frcOFa
