### ISSUE TITLE
Designer-Developer Collaboration

### ISSUE THREAD

**Issue by rchlk** [specfm/design-details#314]
Hey guys, what are some tips for effective designer-developer collaboration? I feel like the design and tech people in my team are working in silos. Any tips to improve this?

Also, how should we do design review for the final developed product? Would like to hear how you guys do it. 

Thanks!

**Comment by brianlovin** [comment]
Some episodes we've recorded in the past that might touch on these topics:
https://designdetails.fm/episodes/315921
https://designdetails.fm/episodes/305860
https://designdetails.fm/episodes/310638

I wonder if those might help answer here, but if you're still left with questions let me know!

**Comment by rchlk** [comment]
hey thanks! will listen to those episodes first

**Comment by brianlovin** [comment]
Great! I'm going to close this for now, but feel free to re-open :)
