### ISSUE TITLE
When to stop fighting for what you know is right

### ISSUE THREAD

**Issue by kemiljk** [specfm/design-details#323]
Sometimes, and we’ve all been there, you know what you’re doing is right. Let’s say, fighting for a darker blue to pass accessibility requirements or visualising data in a simplified graphic rather than a complex multi-dimensional graph, to appeal to a wider audience. You’ve presented this with justification and examples or clear guideline recommendations (say a design system) but it’s ignored. 

How do you guys generally know when to back down and stop fighting for what you know to be right based your design experience, and bow to the Product Manager/Owner’s opinion even if it’s not steeped in fact?

You can use my name yada yada.

**Comment by brianlovin** [comment]
Discussed in 344! https://designdetails.fm/episodes/319554
