### ISSUE TITLE
How to get unstuck when working on complex UX issues?

### ISSUE THREAD

**Issue by jessicaperelman** [specfm/design-details#328]
What are some strategies that less experienced designers can use to get unstuck when working on complex problems?

Let me be more specific. You frame the problem, do your research, and run an energetic brainstorming session with your team. The creative juices are flowing, everyone is happy and excited about the cool new ideas which makes sense to everyone and you can't wait to get started exploring and digging deeper. 

The excitement starts to fade when you begin materializing the ideas and you start seeing these huge gaps in those initial solutions. This may be because you were not thinking about all the use-cases and "what-if" scenarios when coming up with those ideas. Or it could be the case that there are a lot of dots to connect and thinking about solutions starts to feel like solving a very difficult sliding tile puzzle where you get glimpses of hope when you match up a few tiles but realize that you actually screwed up the entire puzzle and have to rearrange everything.

Sorry for the rant, and thanks for making the podcast!

**Comment by brianlovin** [comment]
Discussed in https://designdetails.fm/episodes/320499!
