### ISSUE TITLE
What are the qualities of great design?

### ISSUE THREAD

**Issue by KevinGutowski** [specfm/design-details#334]
I recently rewatched this awesome WWDC talk on quality. https://developer.apple.com/videos/play/wwdc2018/801/

There were some really great questions posed and it would be great to hear your take on them!

Here are some of my notes on what questions stood out to me:
- Designers seem to love to talk about quality… What is quality? What does quality feel like?
    - So how do you design for that? 
    - Intentionality & attention to detail
- How would you describe care?
    - How do you do that? How do you know when you have made progress?
- Why is quality or care important?
    - It can evoke trust, what are some ways you've gotten trust from others (related to your product)? How have you earned it?
- Aspirations
    - Simplicity
        - Why should apps be “simple"? We are constantly thinking through our designs copy & experience and often think to ourselves "its too complex"
        - Why is complexity "bad"?
        - How would you describe simplicity?
        - How do you keep folks from being distracted? How do you keep their focus? Prevent them from feeling overwhelmed?
- What apps have a positive impact on your life?
- Nobody sets out to make a bad app… what makes design so hard?
    - What helps you to make the highest quality work?
    - How do you check your assumptions?
    - When you get feedback how do you resist the temptation to get defensive? especially if you've just spent weeks on trying to get things right?
    - Why is it important to be open to feedback?
    - How do approach designing for so many people?
        - How can you be modest/mindful/skeptical?

**Comment by KevinGutowski** [comment]
What kind of find interesting about the whole talk in general is how close "quality" and “craft” are. Yet it seems like quality has a bit more overarching themes to investigate whereas discussions about craft tend to be more about the placement of pixels.

**Comment by brianlovin** [comment]
Discussed in today's episode, thank you for this great topic! https://designdetails.fm

**Comment by KevinGutowski** [comment]
🙌 thanks for a great discussion! Thought ya’ll would just pick out stuff that resonated the most. Worked out great!
