### ISSUE TITLE
Design systems

### ISSUE THREAD

**Issue by katarinablind** [specfm/design-details#341]
So for a while now, I’ve been wondering about design systems. 
I know that especially for bigger companies with several people working on a project, it can really help to create one unified UI. But I’m curious about whether they can impact creativity. If the design elements are already established, it seems like that takes away quite a bit of the design process. There’s a lot of talk about pixel-pushing and getting the typography, color, alignment, etc. just right. So if that’s taken care of by a design system it appears as if what’s left to design is the combination of elements...
Eager to hear your thoughts.

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/DBfuJ3zn
