### ISSUE TITLE
“I’m not a great graphic designer”

### ISSUE THREAD

**Issue by fabiogiolito** [specfm/design-details#342]
In a recent episode Brian said “I’m not a great graphic designer”. 
I'd love to hear more about this.

Design is a visual medium but there's a misconception that all designers should be good at making pretty things (marketing pages, illustrations, icons, logos…)

I love systems and flows, solving problems and designing interfaces. When I try to make a marketing page or logo I feel frustrated and impostor syndrome kicks in.

I guess I'm not comfortable with the subjectiveness of visual stuff. You know when something is bad, but the gray area of taste and trends is way too big. While in UX there are more rules and logic involved.

This could be an expansion of #327.

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/320285 
Thank you for the question
