### ISSUE TITLE
How to measure growth and progress as a designer?

### ISSUE THREAD

**Issue by jessicaperelman** [specfm/design-details#367]
Two years ago I started my first design role (design team of one at a startup) right after school. I was a junior designer back then and I still **feel like** a junior designer today. There are things that I am better at and I feel a bit more confident in my abilities, but the problem is I don't know how to measure my growth, and I don't know if I am just a slightly better junior designer or I have "graduated" to the next level.

How do you know you are growing as a designer?

**Comment by brianlovin** [comment]
We might have covered this in https://designdetails.fm/episodes/306429 - let me know if that helps!

**Comment by jessicaperelman** [comment]
@brianlovin Thanks. I wasn't aware of this episode. It was very helpful.
