### ISSUE TITLE
Am I actually meant to be a product manager? 

### ISSUE THREAD

**Issue by rachek107** [specfm/design-details#389]
I am a product designer and I work with very talented designers on my team. I constantly find myself trying very hard to push myself up into higher level product discussions and decisions with the product managers since I feel it is part of my job to not just get product requirements handed down and design then, but to be part of the definition. But it seems like no one else on the design team really cares as much and are happy to get very specific requirements and flows. 
So I wonder, is it just my company who doesn’t value product designers role or is it the state of the industry? Would I be happier as a product manager?

**Comment by brianlovin** [comment]
We discussed this question on today's episode! https://designdetails.fm/episodes/GM2_23As

**Comment by rachek107** [comment]
That was awesome! Thanks guys for the advice. I think it all comes down to
mindset, perseverance and getting lucky with a great pm and eng team. I
really liked the point about how different designers can be great at and
put more effort into different things. That's what keeps things
interesting.

**Comment by brianlovin** [comment]
Great to hear :) Also, we're doing an interview next week with a designer-turned-PM, so hopefully we can get some more insights about what the transition would actually look like if you end up going in that direction!

**Comment by brianlovin** [comment]
More discussion on this in today's episode! https://designdetails.fm/episodes/9If3dnMP
