### ISSUE TITLE
GPT-3 and the future of design & technology

### ISSUE THREAD

**Issue by fabiogiolito** [specfm/design-details#405]
How not to talk about GPT-3? Hot takes only. 

Context:
https://www.technologyreview.com/2020/07/20/1005454/openai-machine-learning-language-generator-gpt-3-nlp/

Jordan Singer’s Figma plugin “Designer”:
https://twitter.com/jsngr/status/1284511080715362304?s=20

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/w1HpmWbW

**Comment by fabiogiolito** [comment]
Just listened to it!
Great episode, thanks.
