### ISSUE TITLE
How to get quantitative measurements for user interfaces

### ISSUE THREAD

**Issue by ElliottRoche** [specfm/design-details#423]
Hi guys! Love the show.

I'm curious about how designers test their designs both while they're in development and once they're out in the world and public facing. 

Design tends to be overwhelmingly qualitative in the way people measure and interpret it, so there's always surveys and self-reported measures that you can use, but I'm wondering more about the qualitative, statistical type analyses.
What are some ways to measure user experience or interface "performance" (for lack of a better word)?

There's plenty of optimization tools like Optimizely, VWO, and Google Optimize but they seem to be built for marketing and sales teams and not really for designers or developers who want to know more about how the user interacts with the elements on the screen and not necessarily if they converted to a sale or a sign up or whatever.

**Comment by brianlovin** [comment]
We discussed this in today's episode! https://designdetails.fm/episodes/9paNsXR0
