### ISSUE TITLE
What do full time designers actually do all day?

### ISSUE THREAD

**Issue by lukees** [specfm/design-details#435]
I've worked as a designer in the industry for over a decade, usually straddling development, support, management, and direction duties at the same time. I've now got a full-time design-only job and **honestly don't know how designers fill their days** without dipping into one of those areas I mentioned above (or conducting ongoing user-research).

I imagine part of the issue for me is how I've effectively been a part-time designer this whole time, learning how to make the most of my time in Figma, Sketch, and Photoshop over the years. For instance, I don't bother with pixel-perfection, instead focusing on solid system design, my relationships with developers, and PRing my own detail work from time to time to avoid tedious "polish" tasks.

**Comment by lukees** [comment]
@brianlovin

![excited](https://user-images.githubusercontent.com/28061273/92028815-7c15f300-ed19-11ea-818e-61d7d67bc945.gif)

By the way, I _was_ quoting some engineers I work with, with respect to polish tasks (I personally avoid the term as much as possible). And I should've said I am _the only_ designer where I work and that our company has just one recurring meeting with the whole company so I've literally just got all day to design, with the occasional screenshares with engineers.

I'm gonna try opening up a weekly design critique, but letting anyone drop-in. Thanks for the inspiration!

**Comment by brianlovin** [comment]
Thanks for the question Luke! Episode, for anyone who sees this down the road: https://designdetails.fm/episodes/kNnVXKL4

Totally understand the struggles of being the solo designer at a company - good luck!!
