### ISSUE TITLE
work journaling

### ISSUE THREAD

**Issue by muffmasterflash** [specfm/design-details#441]
Hello! I have a question for Marshall. In the latest episode, you mentioned that you "journal" each day, recording what you worked on, notes and links you might want to reference later, etc. I'm wondering: Do you have a particular tool you use for that? I sometimes create Google docs for notes, but then I have to remember what folder I put it in... and journaling apps like Penzu are a bit too formally structured. I've been looking for something that makes digital note-keeping quick & easy throughout the day, and even better, would be searchable. Any cool things you might recommend?

Thanks! Love you guys!

**Comment by brianlovin** [comment]
Discussed in The Sidebar of today's episode! https://designdetails.fm/episodes/cxSRBzlS
