### ISSUE TITLE
Talking to users

### ISSUE THREAD

**Issue by JosephACooper** [specfm/design-details#449]
Forgive me if you have already done an episode like this (all though from memory I can't remember one). I thought of this question in response to Episode 362 "What do designers do all day?" and noticed neither of you really touched on the research side of product design!

Anyway... I've moved into a new company recently and have luckily had the opportunity to have a lot more customer interaction than in previous companies and I'm loving it. After chatting to several other designers though it made me realise that a lot of other designers and teams tend to really under look the value this can add to building a product. I would love to hear more about in your day jobs you incorporate user feedback, testing and research into building your products. Is this something you do? When do you do it? How often do you do it? etc. I'd also love to know more about how you structure these sessions and ask the right questions to make sure you're extracting the most value possible out of them!

**Comment by brianlovin** [comment]
Discussed today! https://designdetails.fm/episodes/cxSRBzlS

**Comment by JosephACooper** [comment]
Thanks for answering. Absolutely loved this, was great to hear real examples as well as hear how it worked across a range of different companies. Would love to hear more process related discussions with examples like this in future!
