### ISSUE TITLE
How should "Settings" be used properly?

### ISSUE THREAD

**Issue by PriscillaThen** [specfm/design-details#450]
I'm building a very complicated web app and have a few questions: 

1a. What's the difference between "Settings", "Configuration", and "System" (would it be appropriate to have all 3)? 
1b. How should "Settings" be used?

2. Should Settings be displayed visually "apart" from the rest of the first-level navigation options, like how Shopify does it (putting all things in the left sidebar from the top, but the settings at the bottom)? 
<img width="231" alt="Screen Shot 2020-09-07 at 10 29 07 AM" src="https://user-images.githubusercontent.com/2814273/92409302-fe752d00-f0f4-11ea-94fd-90528b15ed1d.png">

3. What do you think of companies that have multiple, tiered settings (like Zoom)? Do you think that they executed it well?

Would love to hear your thoughts, and any by your listeners!

**Comment by lukees** [comment]
I prefer a single home for "Settings", which would ideally contain anything users can _set and forget_. I think this is why it's generally separated from the rest of the top-level navigation, which you're presumably using a lot more often. Also when you think of any piece of software and what it _does_, you wouldn't say "configure settings". So the primary navigation items ideally represent what you _do_ with that software.

**Comment by PriscillaThen** [comment]
Good food for thought, thanks Luke. (Curious to hear other people's opinions also!) :)

**Comment by brianlovin** [comment]
We discussed this in more depth during today's episode, in case it's helpful! https://designdetails.fm/episodes/VHJVnZEo
