### ISSUE TITLE
From web to product design, and other stuff

### ISSUE THREAD

**Issue by drewclem** [specfm/design-details#46]
1. I’ve been working as a designer for a few years. I’ve done some web design projects but never any true product design. Is there a separation between a web and product designer and if so, what are those separations and what would I need to study up on to transition to product design?

2. I work with a team of traditionally print designers and, while they’re good at what they’re trained in, their ideas don’t always transfer to the web very well. What’s the best way to have them drop some of their print antics for web projects?

3. I’m a designer first whose learning to code. How competent do I have to be at each before I become the coveted unicorn? 🦄 Or, should I just pick one and stick to it?

**Comment by brianlovin** [comment]
Discussed in https://spec.fm/podcasts/design-details/315253
