### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by itsmerrisa** [specfm/design-details#606]
Hi guys. I'm new to the design world and recently started a UX bootcamp. I love this podcast so much and was curious your thoughts on something top of mind. It's pretty obvious that this bootcamp will teach super basic foundational stuff but not much more. We use Figma but we spend only a couple weeks "learning" visual design. Do you have a recommended way to explore potential side projects for new kids to expand learning in the visual design space? Much appreciated.

**Comment by brianlovin** [comment]
We talk about this a bit here: https://designdetails.fm/episodes/guyTfHAB

Hopefully that's a good jumping-off point 😊
