### ISSUE TITLE
Designer-developer hand-off process

### ISSUE THREAD

**Issue by mlamond** [specfm/design-details#66]
Could you go over the details of design documentation and developer hand-off? My company uses Axure, but I've been researching other prototyping tools to see if they have better output for developers. I believe you guys use Figma, but after a short tutorial it doesn't look like that provides useful developer resources, either, though I'm new to it so maybe I'm just missing something. What does your designer-developer handoff look like? What's the process you've found that works best for you (and your developers?)

**Comment by Mannnny** [comment]
My company use sketch + Zeplin for handoff.

**Comment by mlamond** [comment]
We use Axure. Only a few of our teammates have Macs, so we need cross-system tools.

**Comment by ryadraws** [comment]
What does a developer hand off consist of? Component positions on a page, colours and fonts?

**Comment by brianlovin** [comment]
Thanks everyone! Discussed in https://spec.fm/podcasts/design-details/315921
