### ISSUE TITLE
What's the best onboarding experience?

### ISSUE THREAD

**Issue by Mannnny** [specfm/design-details#67]
Hi guys,

I have been working on some onboarding stuff for an app, something that can be so easy to understand for designers and devs, but for our very not tech savvy users, it could be a pain. 

There's always those simple onboarding just swipe through a bunch of features that lots of people will just ignore (I'm one of them), and I'm not a big fan of that. What are the best onboarding experience you guys have ever had? And what do you think could define a good onboarding experience? Any tips on making a great onboarding experience for not so tech savvy people?

Thanks!

**Comment by brianlovin** [comment]
We dug into this topic in episode 322! https://spec.fm/podcasts/design-details/312308
