### ISSUE TITLE
Do you use any tools to automate your design process?

### ISSUE THREAD

**Issue by nikitavoloboev** [specfm/design-details#7]
Aside from the big tools like Figma, Sketch. 

Do you use any tools that help with more quickly iterating on new designs? Perhaps something like [Karabiner](https://github.com/tekezo/Karabiner-Elements) or [Alfred](https://www.alfredapp.com)?

**Comment by nikitavoloboev** [comment]
Just listened to the [episode](https://overcast.fm/+EPsKVzJo4). Thanks for covering the question. Will definitely look into writing Figma plugins.

You mentioned that people can link to some automation tools. I made a [macOS repo of all tools I personally use](https://github.com/nikitavoloboev/my-mac-os). Alongside descriptions of how I use them.

The reason I mentioned Karabiner above is that I find it to be by far the most powerful tool you can use to save time in doing things. I wrote [an article](https://medium.com/@nikitavoloboev/karabiner-god-mode-7407a5ddc8f6) going over how you can start using the tool to turn all keys on the keyboard into custom hyper keys. Would be interesting to see if you try it out and maybe adopt this approach as there is very few people that do this, sadly.

**Comment by brianlovin** [comment]
Wow your repo is insanely detailed, I have a lot of open tabs now. Thanks for the recs!
