### ISSUE TITLE
Podcast is not pushed anymore in Pocket Casts

### ISSUE THREAD

**Issue by loucaspapa** [specfm/design-details#708]
HI there 👋 

I just realised that your episodes are not pushed anymore in Pocket Casts. 
The podcast appears as 'Show is on a break or finished.' 

That's all. Take care

**Comment by brianlovin** [comment]
Thanks for the heads up @loucaspapa — I just refreshed in Pocket Casts since our episode came out on Monday and I think it's fixed; we had a delay between our last two episodes so I bet Pocket Casts thought we were on hiatus 😅
