### ISSUE TITLE
How do you manage margins for type styles in Figma?

### ISSUE THREAD

**Issue by JoeyPearlman** [specfm/design-details#709]
Followup on the design system convo wirh a question about text styles and margins!

In css, all the headings and paragraphs and other text styles are going to be defined with specific top/bottom margins, and might even have rules to adapt margin in certain situations. 

So final paragraphs might get extra margin-bottom compared to other paragraphs, or h2 might have one margin-top if it appears directly after an h1, but a different margin-top if it appears after a paragraph. 

Figma doesn’t really have a way to do any of this, so what do you do? Do you even document this in Figma?

**Comment by brianlovin** [comment]
Discussed in this week's episode — thanks for both questions @JoeyPearlman 🙇‍♂️ https://designdetails.fm/episodes/1Cz5Nxiq
